# ---
# tags: nox, config
# crystal-type: source
# crystal-domain: comp
# ---
[package]
name = "nox-cli"
version = "0.2.0"
edition = "2024"
description = "nox command-line interface"
license = "Cyber"

[[bin]]
name = "nox"
path = "main.rs"

[dependencies]
nox = { version = "0.3.0", package = "cyber-nox", path = "../rs" }
nebu = { version = "0.1.1", package = "strata-nebu", path = "../../strata/nebu/rs" }
